import { Table } from 'antd';

export default function Classpage() {
  const columns = [
    {
      title: '연도',
      dataIndex: 'year',
      width: '10%',
      sorter: (a, b) => a.year - b.year,
    },
    {
      title: '학기',
      dataIndex: 'name',
      width: '10%',
      filters: [
        {
          text: '학기구분',
          value: 'Category 1',
          children: [
            {
              text: '1학기',
              value: '1학기',
            },
            {
              text: '2학기',
              value: '2학기',
            },
          ],
        },
      ],
      filterSearch: true,
      onFilter: (value, record) => record.name.includes(value),
    },
    {
      title: '과목명',
      dataIndex: 'address',
      width: '40%',
    },
    {
      title: '등급',
      dataIndex: 'professor',
      filters: [
        {
          text: 'A',
          value: 'A',
        },
        {
          text: 'B',
          value: 'B',
        },
        {
          text: 'C',
          value: 'C',
        },
        {
          text: 'D',
          value: 'D',
        },
        {
          text: 'F',
          value: 'F',
        },
        {
          text: 'S',
          value: 'S',
        },
      ],
      onFilter: (value, record) => record.professor.includes(value),
      filterSearch: true,
      width: '10%',
    },
    {
      title: '구분',
      dataIndex: 'age',
      filters: [
        {
          text: '교선',
          value: '교선',
        },
        {
          text: '기필',
          value: '기필',
        },
        {
          text: '전필',
          value: '전필',
        },
        {
          text: '전선',
          value: '전선',
        },
      ],
      onFilter: (value, record) => record.age.includes(value),
      filterSearch: true,
      width: '10%',
    },
  ];
  const data = [
    {
      key: '1',
      year: '2019',
      name: '1학기',
      address: '철학의 이해',
      professor: "B+",
      age: '교선',
    },
    {
      key: '2',
      year: '2019',
      name: '1학기',
      address: '음악의 이해',
      professor: "C+",
      age: '교선',
    },
    {
      key: '3',
      year: '2019',
      name: '1학기',
      address: '정보문화와 현대사회',
      professor: "B+",
      age: '교선',
    },
    {
      key: '4',
      year: '2019',
      name: '1학기',
      address: '한국사와 한국문화',
      professor: "B+",
      age: '교선',
    },
    {
      key: '5',
      year: '2019',
      name: '1학기',
      address: '경제학원론',
      professor: "A+",
      age: '기필',
    },
    {
      key: '6',
      year: '2019',
      name: '1학기',
      address: '경영학원론',
      professor: "B0",
      age: '전필',
    },
    {
      key: '7',
      year: '2019',
      name: '1학기',
      address: '비즈니스영어',
      professor: "B0",
      age: '기필',
    },
    {
      key: '8',
      year: '2019',
      name: '2학기',
      address: '논리와사고',
      professor: "D+",
      age: '교선',
    },
    {
      key: '9',
      year: '2019',
      name: '2학기',
      address: '창업과경영',
      professor: "C+",
      age: '교선',
    },
    {
      key: '10',
      year: '2019',
      name: '2학기',
      address: '회계원리',
      professor: "C+",
      age: '전필',
    },
    {
      key: '11',
      year: '2019',
      name: '2학기',
      address: '경영수학',
      professor: "D0",
      age: '기필',
    },
    {
      key: '12',
      year: '2019',
      name: '2학기',
      address: '통계학',
      professor: "F",
      age: '기필',
    },
    {
      key: '13',
      year: '2019',
      name: '2학기',
      address: '경영정보처리',
      professor: "C+",
      age: '전필',
    },
    {
      key: '14',
      year: '2019',
      name: '2학기',
      address: '모델링과창의성개발',
      professor: "F",
      age: '교선',
    },
    {
      key: '15',
      year: '2020',
      name: '1학기',
      address: '결혼과가족',
      professor: "S",
      age: '교선',
    },
    {
      key: '16',
      year: '2020',
      name: '1학기',
      address: '진로선택과자기계발',
      professor: "S",
      age: '교선',
    },
    {
      key: '17',
      year: '2020',
      name: '1학기',
      address: '재무회계',
      professor: "B+",
      age: '전필',
    },
    {
      key: '18',
      year: '2020',
      name: '1학기',
      address: '경영통계학',
      professor: "C+",
      age: '전필',
    },
    {
      key: '19',
      year: '2020',
      name: '1학기',
      address: '마케팅',
      professor: "B+",
      age: '전필',
    },
    {
      key: '20',
      year: '2020',
      name: '1학기',
      address: '조직환경론',
      professor: "A0",
      age: '전선',
    },
    {
      key: '21',
      year: '2020',
      name: '1학기',
      address: '창업비즈니스모델개발',
      professor: "S",
      age: '전선',
    },
    {
      key: '22',
      year: '2020',
      name: '2학기',
      address: '논리와사고',
      professor: "B+",
      age: '교선',
    },
    {
      key: '23',
      year: '2020',
      name: '2학기',
      address: '조직행동론',
      professor: "A0",
      age: '전필',
    },
    {
      key: '24',
      year: '2020',
      name: '2학기',
      address: '계량경영학',
      professor: "B+",
      age: '전필',
    },
    {
      key: '25',
      year: '2020',
      name: '2학기',
      address: '소비자행동론',
      professor: "B+",
      age: '전선',
    },
    {
      key: '26',
      year: '2020',
      name: '2학기',
      address: '회계원리',
      professor: "B+",
      age: '전필',
    },
    {
      key: '27',
      year: '2020',
      name: '2학기',
      address: '통계학',
      professor: "B+",
      age: '기필',
    },
    {
      key: '28',
      year: '2020',
      name: '2학기(보충)',
      address: '비판적사고와논증적글쓰기',
      professor: "A+",
      age: '교선',
    },
    {
      key: '29',
      year: '2020',
      name: '2학기(보충)',
      address: '한국문학제대로읽기',
      professor: "A+",
      age: '교선',
    },
    {
      key: '30',
      year: '2021',
      name: '1학기',
      address: '경영정보시스템',
      professor: "C+",
      age: '전선',
    },
    {
      key: '31',
      year: '2021',
      name: '1학기',
      address: '생산관리',
      professor: "B+",
      age: '전필',
    },
    {
      key: '32',
      year: '2021',
      name: '1학기',
      address: '재무관리',
      professor: "B+",
      age: '전필',
    },
    {
      key: '33',
      year: '2021',
      name: '1학기',
      address: '조직설계론',
      professor: "A0",
      age: '전선',
    },
    {
      key: '34',
      year: '2021',
      name: '1학기',
      address: '인적자원관리',
      professor: "A+",
      age: '전필',
    },
    {
      key: '35',
      year: '2021',
      name: '1학기',
      address: '이미지관리와커뮤니케이션',
      professor: "B+",
      age: '교선',
    },
    {
      key: '36',
      year: '2021',
      name: '2학기',
      address: '시의이해',
      professor: "A0",
      age: '교선',
    },
    {
      key: '37',
      year: '2021',
      name: '2학기',
      address: '인간발달',
      professor: "B+",
      age: '교선',
    },
    {
      key: '38',
      year: '2021',
      name: '2학기',
      address: '인본적사고와공동체의가치',
      professor: "S",
      age: '교필',
    },
    {
      key: '39',
      year: '2021',
      name: '2학기',
      address: '국제경영론',
      professor: "B+",
      age: '전필',
    },
    {
      key: '40',
      year: '2021',
      name: '2학기',
      address: '기업재무',
      professor: "B0",
      age: '전필',
    },
    {
      key: '41',
      year: '2021',
      name: '2학기',
      address: '노사관계론',
      professor: 'A0',
      age: '전선',
    },
    {
      key: '42',
      year: '2021',
      name: '2학기',
      address: '전략경영',
      professor: 'B+',
      age: '전선',
    },
    {
      key: '43',
      year: '2021',
      name: '2학기(보충)',
      address: '영화제작에대해알고싶은모든것',
      professor: 'A+',
      age: '교선',
    },
    {
      key: '44',
      year: '2022',
      name: '1학기',
      address: '조직이론',
      professor: 'A+',
      age: '전선',
    },
    {
      key: '45',
      year: '2022',
      name: '1학기',
      address: '대한민국1%가될수있는재테크상식',
      professor: 'F',
      age: '교선',
    },
    {
      key: '46',
      year: '2022',
      name: '1학기',
      address: 'NCS직업기초',
      professor: 'B+',
      age: '교선',
    },
    {
      key: '47',
      year: '2022',
      name: '1학기',
      address: 'SNS로톡하고빅데이터로놀아보자',
      professor: 'B+',
      age: '교선',
    },
    {
      key: '48',
      year: '2023',
      name: '2학기',
      address: '장기현장실습현장실무',
      professor: 'A+',
      age: '전선',
    },
    {
      key: '49',
      year: '2023',
      name: '2학기',
      address: '산업체현장실습',
      professor: 'S',
      age: '전선',
    },
    {
      key: '50',
      year: '2023',
      name: '2학기',
      address: ' 대한민국1%가될수있는재테크상식',
      professor: 'B+',
      age: '교선',
    },
    {
      key: '51',
      year: '2023(보충)',
      name: '2학기',
      address: ' 장기현장실습',
      professor: 'S',
      age: '전선',
    },
  ];
  const onChange = (pagination, filters, sorter, extra) => {
    console.log('params', pagination, filters, sorter, extra);
  };

  return (
    <>
      <p style={{ fontSize: "23px", fontWeight: "bold" }}>수강 및 성적</p>
      <div style={{ height: "20px" }}></div>
      <p style={{ fontSize: "15px" }}>아래의 화살표를 조작해 정렬할 수 있습니다.</p>
      <div style={{ height: "20px" }}></div>
      <div style={{ width: "45vw" }}>
        <Table columns={columns} dataSource={data} onChange={onChange} />
      </div>
    </>
  )
}